export { createDusk } from './adapters/express'
export { loadConfig } from './core/config'
export { RouteMatcher } from './core/matcher'
export { buildHeaders, daysUntilSunset } from './core/headers'
export { checkSunset } from './core/enforcer'
export { createStore } from './core/store'
export type { DuskConfig, EndpointConfig, StoreConfig, LogConfig } from './core/models'
export type { DeprecationHeaders } from './core/headers'
export type { EnforcerResult } from './core/enforcer'  // was wrongly pointing at headers
export type { HitEvent, HitQuery, EndpointSummary, TotalSummary } from './core/store/base'
