export { createDusk } from './adapters/express.js'
export { loadConfig } from './core/config.js'
export { RouteMatcher } from './core/matcher.js'
export { buildHeaders, daysUntilSunset } from './core/headers.js'
export { checkSunset } from './core/enforcer.js'
export type { DuskConfig, EndpointConfig, StoreConfig, LogConfig } from './core/models.js'
export type { DeprecationHeaders, EnforcerResult } from './core/headers.js'
